// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Infrastructure.Persistence;

#nullable disable

namespace ToDoList.Infrastructure.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20240411201610_ToDoItemDetails")]
    partial class ToDoItemDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Domain.Entities.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DoToItems");
                });

            modelBuilder.Entity("ToDoList.Domain.Entities.ToDoItem", b =>
                {
                    b.OwnsOne("ToDoList.Domain.Entities.ToDoItemDetails", "ItemDetails", b1 =>
                        {
                            b1.Property<int>("ToDoItemId")
                                .HasColumnType("int");

                            b1.Property<int>("Category")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Deadline")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Descripton")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ToDoItemId");

                            b1.ToTable("DoToItems");

                            b1.WithOwner()
                                .HasForeignKey("ToDoItemId");
                        });

                    b.Navigation("ItemDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
